apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: {{ template "metabase.fullname" . }}-binding
  namespace: default
spec:
  instanceRef:
    name: {{ template "metabase.fullname" . }}-instance
  secretName: {{ template "metabase.fullname" . }}-database
