---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "sakura-cloud-controller-manager.name" . }}-agent
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sakura-cloud-controller-manager.name" . }}-agent
  namespace: kube-system

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "sakura-cloud-controller-manager.name" . }}-agent
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "sakura-cloud-controller-manager.name" . }}-agent
subjects:
- kind: ServiceAccount
  name: {{ template "sakura-cloud-controller-manager.name" . }}-agent
  namespace: kube-system