apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "sakura-cloud-controller-manager.name" . }}
  namespace: kube-system
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:cloud-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: {{ template "sakura-cloud-controller-manager.name" . }}
  namespace: kube-system
---